name: Build, Push, and Deploy

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build aniruddhss/cartib:latest .

    - name: Push Docker Image
      run: docker push aniruddhss/cartib:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        debug: true
        script: |
          if [ ! -d "/home/ubuntu/cartib-project/.git" ]; then
              git clone https://github.com/aniruddhss/CartiB.git /home/ubuntu/cartib-project
          fi
          cd /home/ubuntu/cartib-project
          git pull origin main
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
