name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: List repository files
      run: ls -alh

    - name: Check Dockerfile name
      run: ls -alh



    - name: Build Docker Image
      run: docker build -f ./Dockerfile -t aniruddhss/cartib:latest

    - name: Push Docker Image
      run: docker push aniruddhss/cartib:latest

